### ISSUE TITLE
An unexecutable error occurs

### ISSUE THREAD

**Issue by imbsky** [asdf-vm/actions#1]
```
plugins/deno/bin/install. Must be executable by asdf
```

**Comment by vic** [comment]
This is the assertion:

https://github.com/asdf-vm/asdf/blob/master/lib/commands/command-plugin-test#L142

Will try to `asdf plugin-test deno` later today.

**Comment by imbsky** [comment]
```
FAILED: Incorrect permissions on /var/folders/sm/qls397w14hgb7rw38_vrlv_c0000gn/T/asdf.XXXX.ChcssnVP/plugins/deno/bin/install. Must be executable by asdf
```

**Comment by imbsky** [comment]
Related issue: https://github.com/asdf-vm/asdf/issues/373

**Comment by imbsky** [comment]
Somehow install script's permission is `644` (`-rw-r--r--`).

**Comment by imbsky** [comment]
Any ideas? @vic @Stratus3D

**Comment by Stratus3D** [comment]
@imbsky I think that is your issue. I cloned down the repo (https://github.com/asdf-community/asdf-deno) and looked at the files, they don't have execute permission:

```
± % ls -al bin
total 16
drwxr-xr-x   4 trevorbrown  staff   128 Jan 10 11:31 .
drwxr-xr-x  11 trevorbrown  staff   352 Jan 10 11:31 ..
-rw-r--r--   1 trevorbrown  staff  1816 Jan 10 11:31 install
-rw-r--r--   1 trevorbrown  staff  1127 Jan 10 11:31 list-all
```

You'll need to set execute permissions on your script. `744` or `755` should be fine. Make sure you commit the permission change to Git.

Closing since this is a valid error.
